# Generated by Django 4.1.2 on 2022-10-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verify_phone',
            new_name='is_verified_phone',
        ),
    ]
